# docker-compose.yml

version: "3.8" # 指定 docker-compose 文件格式的版本

services:
  # 定义一个名为 'db' 的服务，也就是我们的 PostgreSQL 数据库
  db:
    image: postgres:15 
    container_name: firefly_db 
    restart: always 
    ports:
      # 将容器的 5432 端口映射到我们主机的 5432 端口
      # 格式是：<主机端口>:<容器端口>
      # 这样我们的 Nest.js 应用就可以通过 localhost:5432 连接到它
      - "5432:5432"
    environment:
      # 设置数据库的环境变量
      POSTGRES_USER: firefly_user # 数据库用户名
      POSTGRES_PASSWORD: a_very_secret_password # 数据库密码
      POSTGRES_DB: firefly_db # 默认创建的数据库名称
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  # 声明上面用到的数据卷
  # 数据卷是 Docker 中的一种持久化存储机制，用于在容器之间共享数据
  # 即使我们删除了容器，数据也会被保留在本地的 ./postgres-data 目录中
  # 这样我们就可以在重新启动容器时，继续使用之前的数据
  postgres-data:
